### PR TITLE
HPCC-21768 change "//" to "#" in modroxie.pyconf

### PR DESCRIPTION
**Pull request by xwang2713**
Fix the syntax error in /etc/ganglia/modroxie.pyconf
Build: http://10.240.32.243/view/custom/job/CE-Gangliamonitoring-JIRA-21768/
Tested on Ubuntu 18.04

Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com> 
@kunalaswani please review

### CODE REVIEW

**Comment by richardkchapman** [comment]
I think there is a typo in the commit title's JIRA number

**Comment by Michael-Gardner** [comment]
I'll do a test build with this quickly Ming

**Comment by xwang2713** [comment]
yes. fixed

**Comment by Michael-Gardner** [comment]
Built fine when cherry picked against master.

**Pull request merged**
