### PR TITLE
HPCC-16414 Add permissions field to ecm sevice

### PR DESCRIPTION
**Pull request by garonsky**
Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@rpastrana please review
@richardkchapman

**Review by rpastrana — APPROVED** [review]
@garonsky looks fine, as long as feature authorization is indeed deferred to your onMethod logic.

**Comment by garonsky** [comment]
@rpastrana please review again.  Updated permission to be NONE.

**Review by rpastrana — APPROVED** [review]
@garonsky that's fine if your service/methods don't require feature level auth.

**Comment by garonsky** [comment]
My services are all read-only and do not require any special authorization to view the graphs.

**Comment by garonsky** [comment]
@richardkchapman this is ready to merge

**Pull request merged**
