### PR TITLE
HPCC-23793 remove manually detecting compiler version

### PR DESCRIPTION
**Pull request by xwang2713**
cmake will automatically generate full compiler version for C and C++
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexis.com>

@Michael-Gardner please review

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Looks good

**Comment by xwang2713** [comment]
@richardkchapman this is ready to merge

**Comment by richardkchapman** [comment]
Needed for 7.8.0?

**Comment by xwang2713** [comment]
Changed base to candidate-7.8.0

**Comment by richardkchapman** [comment]
Please squash to a single commit

**Comment by xwang2713** [comment]
create a new one

**Pull request closed without merging**
